version: 3.8

services:
  backend:
    build: 
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - .:/opt/app

  mongodb:
    image: mongodb:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME: root
      - MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:data/db
volumes:
  mongo-data:
    driver: local