# Use the official MongoDB image from the Docker Hub
FROM mongo:latest

# Set environment variables (optional)
COPY .env .

# Expose the default MongoDB port
EXPOSE 27017

# Use the default entrypoint for MongoDB
CMD ["mongod"]
